
ARTISTS = [
    'Anderson .Paak',
    'Arctic Monkeys',
    'Beach House',
    'Childish Gambino',
    'Danny Brown',
    'Kanye West',
    'Kid Cudi',
    'King Krule',
    'Little Dragon',
    'MF DOOM',
    'Madvillain',
    'Madvillainy',
    'Nas',
    'OutKast',
    'Sufjan Stevens',
    'Tame Impala',
    'Toro y Moi',
    'UGK',
    'Washed Out',
    'blood orange',
    'chance the rapper',
    'dj screw',
    'dr. dre',
    'earl sweatshirt',
    'flatbush zombie',
    'frank ocean',
    'freddie gibbs',
    'gza',
    'isaiah rashad',
    'j dilla',
    'jamie xx',
    'jay-z',
    'jimi hendrix',
    'john coltranekendrick lamar',
    'madlib',
    'miles davis',
    'nas',
    'nirvana',
    'notorious BIG',
    'pink floyd',
    'raekwon',
    'the avalanches',
    'three six mafia',
    'tyler, the creator',
    'waka flaka flame',
    'wu tang clan',
    'young thug',
    'lil ugly mane',
    'thundercat',
    'solange',
    'justice',
    'vampire weekend',
    'kali uchis',
    'sza',
    'odd future',
    'RZA',
    'allen stone',
    'Three 6 mafia',
    'JPEGMAFIA',
    'jpeg mafia', 
    'Justice', 
    'Daft punk',
    'daftpunk', 
    'playboi carti',
    'mike',
    'grateful dead',
    'slipknot',
    'toro y moi']
